# Generated by fusen: do not edit by hand

#' plot_wordle
#'
#' @param x a data.frame
#' @param y a.data.frame
#' @importFrom magrittr `%>%`
#' @importFrom dplyr mutate
#' @importFrom dplyr bind_rows
#' @importFrom forcats fct_inorder
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 geom_tile
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 geom_text
#' @importFrom ggplot2 scale_fill_manual
#' @importFrom ggplot2 labs
#' @importFrom ggplot2 facet_wrap
#' @importFrom ggplot2 coord_fixed
#' @importFrom ggplot2 theme_minimal
#' @importFrom ggplot2 theme
#' @importFrom ggplot2 element_text
#' @importFrom ggplot2 element_blank
#'
#' @return
#' \code{ggplot} object
#' @export
#'
#' @examples

plot_wordle <- function(x, y) {
  Char <- Match1 <- Text_x <- Text_y <- Tile_x <- Tile_y <- Type <- NULL
  
  result_plot <- bind_rows(list("Your Guess"     = x,
                                "Remaining Keys" = y),
                           .id = "Type") %>%
    mutate(Type = fct_inorder(Type)) %>%
    ggplot() +
    geom_tile(aes(x = Tile_x, y = Tile_y, fill = Match1),
              color = "black", size = 0.75,
              width = 0.9, height = 0.9)  +
    geom_text(aes(x = Text_x, y = Text_y, label = Char),
              color = "white", size = 10) +
    scale_fill_manual(values = c("correct"           = "#6cad64",
                                 "wrong position"    = "#c9b659",
                                 "not in the answer" = "#787c7e",
                                 "?"                 = "gray80")) +
    labs(title = "{woRdle}: Enjoying Wordle with R package names",
         fill = "") +
    facet_wrap(~Type, ncol = 2) +
    coord_fixed(ratio = 1) +
    theme_minimal(base_size = 16) +
    theme(legend.position = "bottom",
          strip.text.x    = element_text(size = 20),
          plot.title      = element_text(size = 25),
          panel.grid      = element_blank(),
          axis.title      = element_blank(),
          axis.text       = element_blank())

  result_plot
}

#' wordle
#'
#' @param answer \code{"installed"}, \code{"cran"}, or any five character.
#' @param strict a logical value (default is \code{FALSE})
#' @importFrom grDevices graphics.off
#' @importFrom utils installed.packages
#' @importFrom dplyr recode
#' @importFrom dplyr case_when
#'
#' @details
#' \describe{
#' \item{\code{answer}}{If \code{"installed"}, a pacakge list is obtained from your PC. If \code{"cran"}, a package list is obtained from CRAN. Also, you can set any answer with five characters.}
#' \item{\code{strict}}{If \code{TRUE}, your guess not in package list is not applicable (default is \code{FALSE}).}
#' }
#'
#' @export
#'
wordle <- function(answer = "installed", strict = FALSE) {

  graphics.off()

  if (answer == "installed") {
    pkg_list <- rownames(installed.packages())
    pkg_list <- pkg_list[nchar(pkg_list) == 5]
    cat(length(pkg_list), "package names retrieved.")
    ans      <- toupper(sample(pkg_list, 1))
  } else if (answer == "cran") {
    cat("Getting package list from CRAN now...\n")
    pkg_list <- tools::CRAN_package_db()[, c("Package")]
    cat(length(pkg_list), "package names retrieved.")
    pkg_list <- pkg_list[nchar(pkg_list) == 5]
    ans      <- toupper(sample(pkg_list, 1))
  } else if (answer == "dic") {

  } else {
    if (nchar(answer) == 5) {
      ans      <- toupper(answer)
    } else {
      stop("Answer must have 5 characters.")
    }
  }

  ans2 <- strsplit(ans, "", fixed = TRUE)[[1]]

  result <- data.frame(
    Trial  = rep(1:6, each = 5),
    Tile_x = rep(1:5, 6),
    Tile_y = rep(6:1, each = 5),
    Text_x = rep(1:5, 6),
    Text_y = rep(6:1, each = 5),
    Char   = "",
    Match1 = "?",
    Match2 = -1
  )

  keylist <- data.frame(
    Trial  = rep(1:6, each = 5),
    Tile_x = rep(1:5, 6),
    Tile_y = rep(6:1, each = 5),
    Text_x = rep(1:5, 6),
    Text_y = rep(6:1, each = 5),
    Char   = c(LETTERS, rep("", 4)),
    Match1 = "?",
    Match2 = -1
  )

  result2 <- ""

  print(plot_wordle(result, keylist))

  for(i in 1:6) {

    text <- readline(prompt = paste0("Input your guess (", 7 - i, " times reamined): "))

    if (strict) {
      while (!(text %in% pkg_list) & answer %in% c("installed", "cran")) {
        cat("{", toupper(text), "} is not in pacakge list.\n", sep = "")
        text <- readline(prompt = paste0("Input your guess (", 7 - i, " times reamined): "))
      }
    }


    while (nchar(text) != 5 | !all(strsplit(toupper(text), "")[[1]] %in% LETTERS)) {
      cat("Guess must have 5 characters. (only alphabets)\n")
      text <- readline(prompt = paste0("Input your guess (", 7 - i, " times reamined): "))
    }

    text       <- toupper(text)
    text_split <- strsplit(text, "")[[1]]

    match1 <- text_split == ans2
    match2 <- text_split %in% ans2
    match3 <- match1 + match2
    match4 <- recode(match3,
                     "2" = "correct",
                     "1" = "wrong position",
                     "0" = "not in the answer")
    match5 <- recode(match3,
                     "2" = "\U0001f7e9",
                     "1" = "\U0001f7e8",
                     "0" = "\u2b1b")

    result$Char[result$Trial == i]   <- text_split
    result$Match1[result$Trial == i] <- match4

    result2 <- paste0(result2,
                     paste(match5, collapse = ""), "\n")

    for (j in 1:length(unique(text_split))) {
      keylist$Match2[keylist$Char %in% text_split[j]] <- max(
        keylist$Match2[keylist$Char %in% text_split[j]],
        match3[j]
      )
    }

    keylist <- keylist %>%
      mutate(Match1 = case_when(Match2 == 2 ~ "correct",
                                Match2 == 1 ~ "wrong position",
                                Match2 == 0 ~ "not in the answer",
                                TRUE        ~ "?"))

    print(plot_wordle(result, keylist))

    if (sum(match3) == 10) {
      cat("Congratulation!!\n")
      cat("Your Record: ", i, " (Answer was {", toupper(ans), "})\n", sep = "")
      cat(result2)
      break()
    }

    if (i == 6) {
      cat("Your Record: Fail... (Answer was {", toupper(ans), "})\n", sep = "")
      cat(result2)
    }

  }

}
